/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MemberController;
import dto.MemberDTO;
import enums.MembersAttr;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reshan Pubudu
 */
public class ViewMembers extends javax.swing.JFrame {

    MemberController memberController;

    /**
     * Creates new form ViewData
     */
    public ViewMembers() {
        initComponents();
        
        this.setTitle("SAC-Old Boy Association");
        this.setIconImage(new ImageIcon(this.getClass().getResource("/icon/Webp.net-resizeimage (4).png")).getImage());
        
        memberController = new MemberController();
        addNewMemberBtn.setVisible(false);
        refresh();

//        search by regNoTxt
        this.getRootPane().registerKeyboardAction((e) -> {
            regNoTxtDefaultAction();
        }, KeyStroke.getKeyStroke(ShortKeyCode.REG_NO_KEY_CODE, KeyEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);

//        search by nameTxt
        this.getRootPane().registerKeyboardAction((e) -> {
            nameTxtDefaultAction();
        }, KeyStroke.getKeyStroke(ShortKeyCode.NAME_KEY_CODE, KeyEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);

//      search by addressTxt
        this.getRootPane().registerKeyboardAction((e) -> {
            addressTxtDefaultAction();
        }, KeyStroke.getKeyStroke(ShortKeyCode.ADDRESS_KEY_CODE, KeyEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);

//      search by allTxt 
        this.getRootPane().registerKeyboardAction((e) -> {
            searchTxtDefaultAction();
        }, KeyStroke.getKeyStroke(ShortKeyCode.SEARCH_ALL_KEY_CODE, KeyEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);

//        refresh allTxt
        this.getRootPane().registerKeyboardAction((e) -> {
            refresh();
        }, KeyStroke.getKeyStroke(ShortKeyCode.REFRESH_KEY_CODE, KeyEvent.CTRL_MASK), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberTbl = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        addNewMemberBtn = new javax.swing.JButton();
        regNoTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Old Boy Association-Members");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        memberTbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        memberTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg.No", "Name", "No.", "Area", "City"
            }
        ));
        jScrollPane1.setViewportView(memberTbl);
        if (memberTbl.getColumnModel().getColumnCount() > 0) {
            memberTbl.getColumnModel().getColumn(0).setMinWidth(120);
            memberTbl.getColumnModel().getColumn(0).setMaxWidth(120);
            memberTbl.getColumnModel().getColumn(2).setMinWidth(200);
            memberTbl.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        homeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        searchTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtMouseClicked(evt);
            }
        });
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/linea_23(0)_32.png"))); // NOI18N

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        addNewMemberBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewMemberBtn.setText("Add New Member");
        addNewMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMemberBtnActionPerformed(evt);
            }
        });

        regNoTxt.setToolTipText("");
        regNoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regNoTxtMouseClicked(evt);
            }
        });
        regNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoTxtActionPerformed(evt);
            }
        });
        regNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regNoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regNoTxtKeyTyped(evt);
            }
        });

        nameTxt.setToolTipText("");
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTxtMouseClicked(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });

        addressTxt.setToolTipText("");
        addressTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTxtMouseClicked(evt);
            }
        });
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(regNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNewMemberBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(searchTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(refreshBtn)
                    .addComponent(addNewMemberBtn))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        searchMember(MembersAttr.ANY, searchTxt.getText());
    }//GEN-LAST:event_searchTxtKeyReleased

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
    }//GEN-LAST:event_searchTxtKeyTyped

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        refresh();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void addNewMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMemberBtnActionPerformed
        AddMembers addMembers = new AddMembers();
        addMembers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNewMemberBtnActionPerformed

    private void regNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNoTxtKeyReleased
        searchMember(MembersAttr.REGNO, regNoTxt.getText());
    }//GEN-LAST:event_regNoTxtKeyReleased

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        searchMember(MembersAttr.NAME, nameTxt.getText());
    }//GEN-LAST:event_nameTxtKeyReleased

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
        searchMember(MembersAttr.ADDRESS, addressTxt.getText());
    }//GEN-LAST:event_addressTxtKeyReleased

    private void regNoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNoTxtKeyTyped
    }//GEN-LAST:event_regNoTxtKeyTyped

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
    }//GEN-LAST:event_nameTxtKeyTyped

    private void addressTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyTyped
    }//GEN-LAST:event_addressTxtKeyTyped

    private void regNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoTxtActionPerformed
    }//GEN-LAST:event_regNoTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
    }//GEN-LAST:event_nameTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
    }//GEN-LAST:event_addressTxtActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
    }//GEN-LAST:event_searchTxtActionPerformed

    private void regNoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regNoTxtMouseClicked
        regNoTxtDefaultAction();
    }//GEN-LAST:event_regNoTxtMouseClicked

    private void nameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtMouseClicked
        nameTxtDefaultAction();
    }//GEN-LAST:event_nameTxtMouseClicked

    private void addressTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTxtMouseClicked
        addressTxtDefaultAction();
    }//GEN-LAST:event_addressTxtMouseClicked

    private void searchTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTxtMouseClicked
        searchTxtDefaultAction();
    }//GEN-LAST:event_searchTxtMouseClicked

    private void regNoTxtDefaultAction() {
        if (regNoTxt.getText().equals(TextFieldDefaultTest.SEARCH_BY_REG_NO_TEXT)) {
            regNoTxt.setText("");
        } else {
            regNoTxt.selectAll();
        }
        regNoTxt.setForeground(Color.BLACK);
        regNoTxt.requestFocus();
        nameTxt.setText(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT);
        nameTxt.setForeground(Color.LIGHT_GRAY);
        addressTxt.setText(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT);
        addressTxt.setForeground(Color.LIGHT_GRAY);
        searchTxt.setText(TextFieldDefaultTest.SEARCH_ALL_TEXT);
        searchTxt.setForeground(Color.LIGHT_GRAY);
    }

    private void nameTxtDefaultAction() {
        regNoTxt.setText(TextFieldDefaultTest.SEARCH_BY_REG_NO_TEXT);
        regNoTxt.setForeground(Color.LIGHT_GRAY);
        if (nameTxt.getText().equals(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT)) {
            nameTxt.setText("");
        } else {
            nameTxt.selectAll();
        }
        nameTxt.setForeground(Color.BLACK);
        nameTxt.requestFocus();
        addressTxt.setText(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT);
        addressTxt.setForeground(Color.LIGHT_GRAY);
        searchTxt.setText(TextFieldDefaultTest.SEARCH_ALL_TEXT);
        searchTxt.setForeground(Color.LIGHT_GRAY);
    }

    private void addressTxtDefaultAction() {
        regNoTxt.setText(TextFieldDefaultTest.SEARCH_BY_REG_NO_TEXT);
        regNoTxt.setForeground(Color.LIGHT_GRAY);
        nameTxt.setText(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT);
        nameTxt.setForeground(Color.LIGHT_GRAY);
        if (addressTxt.getText().equals(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT)) {
            addressTxt.setText("");
        } else {
            addressTxt.selectAll();
        }
        addressTxt.setForeground(Color.BLACK);
        addressTxt.requestFocus();
        searchTxt.setText(TextFieldDefaultTest.SEARCH_ALL_TEXT);
        searchTxt.setForeground(Color.LIGHT_GRAY);
    }

    private void searchTxtDefaultAction() {
        regNoTxt.setText(TextFieldDefaultTest.SEARCH_BY_REG_NO_TEXT);
        regNoTxt.setForeground(Color.LIGHT_GRAY);
        nameTxt.setText(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT);
        nameTxt.setForeground(Color.LIGHT_GRAY);
        addressTxt.setText(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT);
        addressTxt.setForeground(Color.LIGHT_GRAY);
        if (searchTxt.getText().equals(TextFieldDefaultTest.SEARCH_ALL_TEXT)) {
            searchTxt.setText("");
        } else {
            searchTxt.selectAll();
        }
        searchTxt.setForeground(Color.BLACK);
        searchTxt.requestFocus();
    }

    private void refresh() {
        regNoTxt.setText("");
        regNoTxt.setForeground(Color.BLACK);
        regNoTxt.requestFocus();
        nameTxt.setText(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT);
        nameTxt.setForeground(Color.LIGHT_GRAY);
        addressTxt.setText(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT);
        addressTxt.setForeground(Color.LIGHT_GRAY);
        searchTxt.setText(TextFieldDefaultTest.SEARCH_ALL_TEXT);
        searchTxt.setForeground(Color.LIGHT_GRAY);
        searchMember(MembersAttr.ALL, "");
    }

    private void searchMember(MembersAttr where, String what) {
        if (!what.equals(TextFieldDefaultTest.SEARCH_BY_REG_NO_TEXT) || !what.equals(TextFieldDefaultTest.SEARCH_BY_NAME_TEXT) || !what.equals(TextFieldDefaultTest.SEARCH_BY_ADDRESS_TEXT) || !what.equals(TextFieldDefaultTest.SEARCH_ALL_TEXT)) {
            List<MemberDTO> memberses = memberController.searchMembers(where, what);
            DefaultTableModel dtm = (DefaultTableModel) memberTbl.getModel();
            dtm.setRowCount(0);
            for (MemberDTO memberse : memberses) {
                Object o[] = {memberse.getRegNo(), memberse.getName(), memberse.getNo(), memberse.getArea(), memberse.getCity()};
                dtm.addRow(o);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewMemberBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memberTbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField regNoTxt;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}

class TextFieldDefaultTest {

    public final static String SEARCH_BY_REG_NO_TEXT = "Ctrl+I";
    public final static String SEARCH_BY_NAME_TEXT = "Ctrl+N";
    public final static String SEARCH_BY_ADDRESS_TEXT = "Ctrl+D";
    public final static String SEARCH_ALL_TEXT = "Ctrl+F";
    public final static String REFRESH_TEXT = "Ctrl+R";
}

class ShortKeyCode {

    public final static int REG_NO_KEY_CODE = KeyEvent.VK_I;
    public final static int NAME_KEY_CODE = KeyEvent.VK_N;
    public final static int ADDRESS_KEY_CODE = KeyEvent.VK_D;
    public final static int SEARCH_ALL_KEY_CODE = KeyEvent.VK_F;
    public final static int REFRESH_KEY_CODE = KeyEvent.VK_R;
}
