/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MemberController;
import entity.Members;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.Iterator;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Reshan Pubudu
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    MemberController memberController;

    public Add() {
        initComponents();
        memberController = new MemberController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTbl = new javax.swing.JTable();
        startLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        resultTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTbl);
        if (resultTbl.getColumnModel().getColumnCount() > 0) {
            resultTbl.getColumnModel().getColumn(1).setMinWidth(200);
            resultTbl.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(startLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        startLbl.setText("Started");
//        addValuesTest();
        addValues();
    }//GEN-LAST:event_addBtnActionPerformed

//    public void addValuesTest(){
//        try {
//            if(memberController.addMember(new Members("0007", "name", "initials", "no", "area", "city"))){
//                System.out.println("true");
//            } else 
//                System.err.println("false");
//        } catch (Exception ex) {
//            Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
    public void addValues() {
        InputStream excelFileToRead = null;
        DefaultTableModel dtm = (DefaultTableModel) resultTbl.getModel();
        try {
            Properties dbProperties = new Properties();
            FileReader dbFileReader;
            try {
                dbFileReader = new FileReader(new File("settings/externalpath.properties"));
                dbProperties.load(dbFileReader);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex);
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            }

            excelFileToRead = new FileInputStream(dbProperties.getProperty("path"));
            XSSFWorkbook wb = new XSSFWorkbook(excelFileToRead);
            XSSFSheet sheet = wb.getSheetAt(0);
            Iterator rows = sheet.rowIterator();
            int i = 0;
            while (rows.hasNext()) {
//            while (i < 10) {
                i++;
                XSSFRow row = (XSSFRow) rows.next();

                String regNo = ("" + row.getCell(0)).trim();
                String name = ("" + row.getCell(1)).trim();
                String no = ("" + row.getCell(2)).trim();
                String area = ("" + row.getCell(3)).trim();
                String city = ("" + row.getCell(4)).trim();

                String stringOnly = regNo.replaceAll("[^A-Za-z]", "");
                String numberOnly = regNo.replaceAll("[^0-9]", "");

                if (stringOnly.equals("")) {
                    numberOnly = numberOnly.substring(0, numberOnly.length() - 1);
                    while (numberOnly.length() != 4) {
                        numberOnly = "0" + numberOnly;
                    }
                    regNo = numberOnly;
                }

                if (i > Integer.parseInt(dbProperties.getProperty("start_row_number"))) {
                    regNo = regNo.equals("null") ? "" : regNo;
                    name = name.equals("null") ? "" : name;
                    no = no.equals("null") ? "" : no;
                    area = area.equals("null") ? "" : area;
                    city = city.equals("null") ? "" : city;

                    Members members = new Members(regNo, name, "", no, area, city);
                    try {
                        if (!(members.getRegNo().equals("") && members.getName().equals("") && members.getInitials().equals("") && members.getNo().equals("") && members.getArea().equals("") && members.getCity().equals(""))) {
                            memberController.addMember(members);
                        }
                    } catch (Exception ex) {
                        Object[] o = {regNo + "\t\t" + name + "\t" + no + "\t" + area + "\t" + city, "Added Failed"};
                        dtm.addRow(o);
                        Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
        }
        startLbl.setText("Success");
        addBtn.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable resultTbl;
    private javax.swing.JLabel startLbl;
    // End of variables declaration//GEN-END:variables
}
